use_frameworks!

platform :ios, '9.0'

target 'Feature_Example' do
  pod 'Feature', :path => '../'

  target 'Feature_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
